set -e

# sft-pt-starcoder2-text2plsql-3b on simple dataset
accelerate launch train_causal_lm.py --per_device_train_batch_size 4 --block_size 8192 --seed 42 --pretrained_model_name_or_path /home/zhanghang/opt/models/pt-starcoder2-text2plsql-3b --epochs 2 --lr 5e-6 --warmup_ratio 0.05 --checkpointing_steps 100000 --tensorboard_log_dir ./train_logs/sft-pt-starcoder2-text2plsql-3b-simple --mode sft --output_ckpt_dir ./ckpts/sft-pt-starcoder2-text2plsql-3b-simple --text2sql_data_dir /home/zhanghang/opt/projects/researchprojects/text2PLSQL/experiments/data/data_simple_train_1500.json --table_num 6 --column_num 10

accelerate launch train_causal_lm.py --per_device_train_batch_size 4 --block_size 8192 --seed 42 --pretrained_model_name_or_path /home/zhanghang/opt/models/pt-starcoder2-text2plsql-7b --epochs 2 --lr 5e-6 --warmup_ratio 0.05 --checkpointing_steps 100000 --tensorboard_log_dir ./train_logs/sft-pt-starcoder2-text2plsql-7b-simple --mode sft --output_ckpt_dir ./ckpts/sft-pt-starcoder2-text2plsql-7b-simple --text2sql_data_dir /home/zhanghang/opt/projects/researchprojects/text2PLSQL/experiments/data/data_simple_train_1500.json --table_num 6 --column_num 10

accelerate launch train_causal_lm.py --per_device_train_batch_size 2 --block_size 8192 --seed 42 --pretrained_model_name_or_path /home/zhanghang/opt/models/pt-starcoder2-text2plsql-15b --epochs 2 --lr 5e-6 --warmup_ratio 0.05 --checkpointing_steps 100000 --tensorboard_log_dir ./train_logs/sft-pt-starcoder2-text2plsql-15b-simple --mode sft --output_ckpt_dir ./ckpts/sft-pt-starcoder2-text2plsql-15b-simple --text2sql_data_dir /home/zhanghang/opt/projects/researchprojects/text2PLSQL/experiments/data/data_simple_train_1500.json --table_num 6 --column_num 10

# sft-pt-starcoder2-text2plsql-3b on hard dataset
accelerate launch train_causal_lm.py --per_device_train_batch_size 4 --block_size 8192 --seed 42 --pretrained_model_name_or_path /home/zhanghang/opt/models/pt-starcoder2-text2plsql-3b --epochs 2 --lr 5e-6 --warmup_ratio 0.05 --checkpointing_steps 100000 --tensorboard_log_dir ./train_logs/sft-pt-starcoder2-text2plsql-3b-hard --mode sft --output_ckpt_dir ./ckpts/sft-pt-starcoder2-text2plsql-3b-hard --text2sql_data_dir /home/zhanghang/opt/projects/researchprojects/text2PLSQL/experiments/data/data_hard_train_1500.json --table_num 6 --column_num 10

accelerate launch train_causal_lm.py --per_device_train_batch_size 4 --block_size 8192 --seed 42 --pretrained_model_name_or_path /home/zhanghang/opt/models/pt-starcoder2-text2plsql-7b --epochs 2 --lr 5e-6 --warmup_ratio 0.05 --checkpointing_steps 100000 --tensorboard_log_dir ./train_logs/sft-pt-starcoder2-text2plsql-7b-hard --mode sft --output_ckpt_dir ./ckpts/sft-pt-starcoder2-text2plsql-7b-hard --text2sql_data_dir /home/zhanghang/opt/projects/researchprojects/text2PLSQL/experiments/data/data_hard_train_1500.json --table_num 6 --column_num 10

accelerate launch train_causal_lm.py --per_device_train_batch_size 2 --block_size 8192 --seed 42 --pretrained_model_name_or_path /home/zhanghang/opt/models/pt-starcoder2-text2plsql-15b --epochs 2 --lr 5e-6 --warmup_ratio 0.05 --checkpointing_steps 100000 --tensorboard_log_dir ./train_logs/sft-pt-starcoder2-text2plsql-15b-hard --mode sft --output_ckpt_dir ./ckpts/sft-pt-starcoder2-text2plsql-15b-hard --text2sql_data_dir /home/zhanghang/opt/projects/researchprojects/text2PLSQL/experiments/data/data_hard_train_1500.json --table_num 6 --column_num 10